### ISSUE TITLE
cl-arrows is proprietary software

### ISSUE THREAD

**Issue by phoe** [alex-gutev/static-dispatch#2]
cl-arrows [does not have a license file](https://github.com/nightfly19/cl-arrows/issues/5) which makes it proprietary software.

Consider switching to another arrow macro library, such as [arrows](https://github.com/Harleqin/arrows), [arrow-macros](https://github.com/hipeta/arrow-macros), or (shameless plug) [binding-arrows](https://github.com/phoe/binding-arrows).

**Comment by alex-gutev** [comment]
Fixed in 6243afcd152854c52ba33daef7394367b657d9c6
