### ISSUE TITLE
method-descriptions are not honored

### ISSUE THREAD

**Issue by mfiano** [alex-gutev/static-dispatch#8]
[method-description](http://www.lispworks.com/documentation/HyperSpec/Body/m_defgen.htm)s are not honored for `static-dispatch:defgeneric` forms, and dispatch falls back to dynamic mode.

It would be nice to support methods installed in this way, or extend the warning capability to inform the user of such a fallback.

**Comment by alex-gutev** [comment]
They should be honoured. Do you have an example of when they aren't?

**Comment by mfiano** [comment]
I apologize. I am not sure why it wasn't working before but I can no longer reproduce this.
